import 'package:aktivite/core/config/repository_source.dart';
import 'package:aktivite/shared/providers/repository_factories.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('repository factories', () {
    test('in-memory source builds local implementations', () {
      expect(
        buildAuthRepository(RepositorySource.inMemory).runtimeType.toString(),
        'InMemoryAuthRepository',
      );
      expect(
        buildActivityRepository(RepositorySource.inMemory)
            .runtimeType
            .toString(),
        'InMemoryActivityRepository',
      );
      expect(
        buildJoinRequestRepository(RepositorySource.inMemory)
            .runtimeType
            .toString(),
        'InMemoryJoinRequestRepository',
      );
      expect(
        buildChatRepository(RepositorySource.inMemory).runtimeType.toString(),
        'InMemoryChatRepository',
      );
      expect(
        buildProfileRepository(RepositorySource.inMemory)
            .runtimeType
            .toString(),
        'InMemoryProfileRepository',
      );
      expect(
        buildSafetyRepository(RepositorySource.inMemory).runtimeType.toString(),
        'InMemorySafetyRepository',
      );
      expect(
        buildModerationRepository(RepositorySource.inMemory)
            .runtimeType
            .toString(),
        'InMemoryModerationRepository',
      );
      expect(
        buildAnalyticsService(RepositorySource.inMemory).runtimeType.toString(),
        'InMemoryAnalyticsService',
      );
      expect(
        buildRemoteConfigService(RepositorySource.inMemory)
            .runtimeType
            .toString(),
        'InMemoryRemoteConfigService',
      );
    });

    test('firebase source builds firebase-backed implementations', () {
      expect(
        buildAuthRepository(RepositorySource.firebase).runtimeType.toString(),
        'FirebaseAuthRepository',
      );
      expect(
        buildActivityRepository(RepositorySource.firebase)
            .runtimeType
            .toString(),
        'FirestoreActivityRepository',
      );
      expect(
        buildJoinRequestRepository(RepositorySource.firebase)
            .runtimeType
            .toString(),
        'FirestoreJoinRequestRepository',
      );
      expect(
        buildChatRepository(RepositorySource.firebase).runtimeType.toString(),
        'FirestoreChatRepository',
      );
      expect(
        buildProfileRepository(RepositorySource.firebase)
            .runtimeType
            .toString(),
        'FirestoreProfileRepository',
      );
      expect(
        buildModerationRepository(RepositorySource.firebase)
            .runtimeType
            .toString(),
        'FirestoreModerationRepository',
      );
      expect(
        buildSafetyRepository(RepositorySource.firebase).runtimeType.toString(),
        'FirestoreSafetyRepository',
      );
      expect(
        buildAnalyticsService(RepositorySource.firebase).runtimeType.toString(),
        'FirebaseAnalyticsService',
      );
      expect(
        buildRemoteConfigService(RepositorySource.firebase)
            .runtimeType
            .toString(),
        'FirebaseRemoteConfigService',
      );
    });
  });
}
