// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2GFSr9YJpUmC-PoaTKE0yGodyzqYcq6w',
    appId: '1:310514488602:web:23c07f88ae970f6c9a88a3',
    messagingSenderId: '310514488602',
    projectId: 'nar-rehberi',
    authDomain: 'nar-rehberi.firebaseapp.com',
    databaseURL: 'https://nar-rehberi-default-rtdb.firebaseio.com',
    storageBucket: 'nar-rehberi.firebasestorage.app',
    measurementId: 'G-D4SW5LNFTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5acc2-V7kTa3eA3ehMeSVYpoSqdYvSOc',
    appId: '1:310514488602:android:d07adcc11fea081b9a88a3',
    messagingSenderId: '310514488602',
    projectId: 'nar-rehberi',
    databaseURL: 'https://nar-rehberi-default-rtdb.firebaseio.com',
    storageBucket: 'nar-rehberi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4vGonG4ag62KRULwBj7s4ysPw6gfNQo',
    appId: '1:310514488602:ios:f232edb5efc1ff8e9a88a3',
    messagingSenderId: '310514488602',
    projectId: 'nar-rehberi',
    databaseURL: 'https://nar-rehberi-default-rtdb.firebaseio.com',
    storageBucket: 'nar-rehberi.firebasestorage.app',
    androidClientId:
        '310514488602-i77rlej2vq3jb6gk991o222lsgapdvro.apps.googleusercontent.com',
    iosClientId:
        '310514488602-q1b0d5dnipv4hbtqigcfc0h7ophi3bh6.apps.googleusercontent.com',
    iosBundleId: 'com.togio.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2GFSr9YJpUmC-PoaTKE0yGodyzqYcq6w',
    appId: '1:310514488602:web:23c07f88ae970f6c9a88a3',
    messagingSenderId: '310514488602',
    projectId: 'nar-rehberi',
    authDomain: 'nar-rehberi.firebaseapp.com',
    databaseURL: 'https://nar-rehberi-default-rtdb.firebaseio.com',
    storageBucket: 'nar-rehberi.firebasestorage.app',
    measurementId: 'G-D4SW5LNFTD',
  );
}
